# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-31 13:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180530_0730'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='jianshu',
            field=models.CharField(blank=True, max_length=180, verbose_name='\u6982\u8981'),
        ),
    ]
